
package business.handler.sale.product;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InsertSaleProductHandler", targetNamespace = "http://product.sale.handler.business/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InsertSaleProductHandler {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "insertSaleProduct", targetNamespace = "http://product.sale.handler.business/", className = "business.handler.sale.product.InsertSaleProduct")
    @ResponseWrapper(localName = "insertSaleProductResponse", targetNamespace = "http://product.sale.handler.business/", className = "business.handler.sale.product.InsertSaleProductResponse")
    public void insertSaleProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws ApplicationException_Exception
    ;

}
