
package business.handler;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddCustomerHandler", targetNamespace = "http://handler.business/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddCustomerHandler {


    /**
     * 
     * @return
     *     returns java.util.List<business.handler.Discount>
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDiscounts", targetNamespace = "http://handler.business/", className = "business.handler.GetDiscounts")
    @ResponseWrapper(localName = "getDiscountsResponse", targetNamespace = "http://handler.business/", className = "business.handler.GetDiscountsResponse")
    public List<Discount> getDiscounts()
        throws ApplicationException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addCustomer", targetNamespace = "http://handler.business/", className = "business.handler.AddCustomer")
    @ResponseWrapper(localName = "addCustomerResponse", targetNamespace = "http://handler.business/", className = "business.handler.AddCustomerResponse")
    public void addCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3)
        throws ApplicationException_Exception
    ;

}
