
package business.handler.sale;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddSaleHandlerService", targetNamespace = "http://sale.handler.business/", wsdlLocation = "http://localhost:8080/domain-model-ee-business/AddSaleHandler?wsdl")
public class AddSaleHandlerService
    extends Service
{

    private final static URL ADDSALEHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDSALEHANDLERSERVICE_EXCEPTION;
    private final static QName ADDSALEHANDLERSERVICE_QNAME = new QName("http://sale.handler.business/", "AddSaleHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/domain-model-ee-business/AddSaleHandler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDSALEHANDLERSERVICE_WSDL_LOCATION = url;
        ADDSALEHANDLERSERVICE_EXCEPTION = e;
    }

    public AddSaleHandlerService() {
        super(__getWsdlLocation(), ADDSALEHANDLERSERVICE_QNAME);
    }

    public AddSaleHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDSALEHANDLERSERVICE_QNAME, features);
    }

    public AddSaleHandlerService(URL wsdlLocation) {
        super(wsdlLocation, ADDSALEHANDLERSERVICE_QNAME);
    }

    public AddSaleHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDSALEHANDLERSERVICE_QNAME, features);
    }

    public AddSaleHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddSaleHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddSaleHandler
     */
    @WebEndpoint(name = "AddSaleHandlerPort")
    public AddSaleHandler getAddSaleHandlerPort() {
        return super.getPort(new QName("http://sale.handler.business/", "AddSaleHandlerPort"), AddSaleHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddSaleHandler
     */
    @WebEndpoint(name = "AddSaleHandlerPort")
    public AddSaleHandler getAddSaleHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sale.handler.business/", "AddSaleHandlerPort"), AddSaleHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDSALEHANDLERSERVICE_EXCEPTION!= null) {
            throw ADDSALEHANDLERSERVICE_EXCEPTION;
        }
        return ADDSALEHANDLERSERVICE_WSDL_LOCATION;
    }

}
