
package business.handler.sale;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CloseSaleHandlerService", targetNamespace = "http://sale.handler.business/", wsdlLocation = "http://localhost:8080/domain-model-ee-business/CloseSaleHandler?wsdl")
public class CloseSaleHandlerService
    extends Service
{

    private final static URL CLOSESALEHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLOSESALEHANDLERSERVICE_EXCEPTION;
    private final static QName CLOSESALEHANDLERSERVICE_QNAME = new QName("http://sale.handler.business/", "CloseSaleHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/domain-model-ee-business/CloseSaleHandler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLOSESALEHANDLERSERVICE_WSDL_LOCATION = url;
        CLOSESALEHANDLERSERVICE_EXCEPTION = e;
    }

    public CloseSaleHandlerService() {
        super(__getWsdlLocation(), CLOSESALEHANDLERSERVICE_QNAME);
    }

    public CloseSaleHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLOSESALEHANDLERSERVICE_QNAME, features);
    }

    public CloseSaleHandlerService(URL wsdlLocation) {
        super(wsdlLocation, CLOSESALEHANDLERSERVICE_QNAME);
    }

    public CloseSaleHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLOSESALEHANDLERSERVICE_QNAME, features);
    }

    public CloseSaleHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CloseSaleHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CloseSaleHandler
     */
    @WebEndpoint(name = "CloseSaleHandlerPort")
    public CloseSaleHandler getCloseSaleHandlerPort() {
        return super.getPort(new QName("http://sale.handler.business/", "CloseSaleHandlerPort"), CloseSaleHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CloseSaleHandler
     */
    @WebEndpoint(name = "CloseSaleHandlerPort")
    public CloseSaleHandler getCloseSaleHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sale.handler.business/", "CloseSaleHandlerPort"), CloseSaleHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLOSESALEHANDLERSERVICE_EXCEPTION!= null) {
            throw CLOSESALEHANDLERSERVICE_EXCEPTION;
        }
        return CLOSESALEHANDLERSERVICE_WSDL_LOCATION;
    }

}
