
package business.handler.sale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetSaleHandler", targetNamespace = "http://sale.handler.business/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetSaleHandler {


    /**
     * 
     * @param arg0
     * @return
     *     returns business.handler.sale.Sale
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSale", targetNamespace = "http://sale.handler.business/", className = "business.handler.sale.GetSale")
    @ResponseWrapper(localName = "getSaleResponse", targetNamespace = "http://sale.handler.business/", className = "business.handler.sale.GetSaleResponse")
    public Sale getSale(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ApplicationException_Exception
    ;

}
