
package business.handler.sale;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetSaleHandlerService", targetNamespace = "http://sale.handler.business/", wsdlLocation = "http://localhost:8080/domain-model-ee-business/GetSaleHandler?wsdl")
public class GetSaleHandlerService
    extends Service
{

    private final static URL GETSALEHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETSALEHANDLERSERVICE_EXCEPTION;
    private final static QName GETSALEHANDLERSERVICE_QNAME = new QName("http://sale.handler.business/", "GetSaleHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/domain-model-ee-business/GetSaleHandler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETSALEHANDLERSERVICE_WSDL_LOCATION = url;
        GETSALEHANDLERSERVICE_EXCEPTION = e;
    }

    public GetSaleHandlerService() {
        super(__getWsdlLocation(), GETSALEHANDLERSERVICE_QNAME);
    }

    public GetSaleHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETSALEHANDLERSERVICE_QNAME, features);
    }

    public GetSaleHandlerService(URL wsdlLocation) {
        super(wsdlLocation, GETSALEHANDLERSERVICE_QNAME);
    }

    public GetSaleHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETSALEHANDLERSERVICE_QNAME, features);
    }

    public GetSaleHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetSaleHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetSaleHandler
     */
    @WebEndpoint(name = "GetSaleHandlerPort")
    public GetSaleHandler getGetSaleHandlerPort() {
        return super.getPort(new QName("http://sale.handler.business/", "GetSaleHandlerPort"), GetSaleHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetSaleHandler
     */
    @WebEndpoint(name = "GetSaleHandlerPort")
    public GetSaleHandler getGetSaleHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sale.handler.business/", "GetSaleHandlerPort"), GetSaleHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETSALEHANDLERSERVICE_EXCEPTION!= null) {
            throw GETSALEHANDLERSERVICE_EXCEPTION;
        }
        return GETSALEHANDLERSERVICE_WSDL_LOCATION;
    }

}
