
package business.handler.sale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaySaleHandler", targetNamespace = "http://sale.handler.business/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaySaleHandler {


    /**
     * 
     * @param arg0
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "paySale", targetNamespace = "http://sale.handler.business/", className = "business.handler.sale.PaySale")
    @ResponseWrapper(localName = "paySaleResponse", targetNamespace = "http://sale.handler.business/", className = "business.handler.sale.PaySaleResponse")
    public void paySale(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ApplicationException_Exception
    ;

}
