
package business.handler.sale;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaySaleHandlerService", targetNamespace = "http://sale.handler.business/", wsdlLocation = "http://localhost:8080/domain-model-ee-business/PaySaleHandler?wsdl")
public class PaySaleHandlerService
    extends Service
{

    private final static URL PAYSALEHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYSALEHANDLERSERVICE_EXCEPTION;
    private final static QName PAYSALEHANDLERSERVICE_QNAME = new QName("http://sale.handler.business/", "PaySaleHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/domain-model-ee-business/PaySaleHandler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYSALEHANDLERSERVICE_WSDL_LOCATION = url;
        PAYSALEHANDLERSERVICE_EXCEPTION = e;
    }

    public PaySaleHandlerService() {
        super(__getWsdlLocation(), PAYSALEHANDLERSERVICE_QNAME);
    }

    public PaySaleHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYSALEHANDLERSERVICE_QNAME, features);
    }

    public PaySaleHandlerService(URL wsdlLocation) {
        super(wsdlLocation, PAYSALEHANDLERSERVICE_QNAME);
    }

    public PaySaleHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYSALEHANDLERSERVICE_QNAME, features);
    }

    public PaySaleHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaySaleHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaySaleHandler
     */
    @WebEndpoint(name = "PaySaleHandlerPort")
    public PaySaleHandler getPaySaleHandlerPort() {
        return super.getPort(new QName("http://sale.handler.business/", "PaySaleHandlerPort"), PaySaleHandler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaySaleHandler
     */
    @WebEndpoint(name = "PaySaleHandlerPort")
    public PaySaleHandler getPaySaleHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sale.handler.business/", "PaySaleHandlerPort"), PaySaleHandler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYSALEHANDLERSERVICE_EXCEPTION!= null) {
            throw PAYSALEHANDLERSERVICE_EXCEPTION;
        }
        return PAYSALEHANDLERSERVICE_WSDL_LOCATION;
    }

}
